# Generated by Django 4.0.4 on 2022-06-24 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComingSoonMailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='course_categories',
            fields=[
                ('category_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=200, primary_key='True', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=200)),
                ('display_image', models.ImageField(upload_to='images/course_image/display_images/')),
                ('course_price', models.CharField(default='Free', max_length=200)),
                ('apply_link', models.URLField(default='#')),
                ('course_summary', models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400)),
                ('course_prerequisites', models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400)),
                ('course_eligibility', models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400)),
                ('course_syllabus', models.FileField(default='pdf/syllabus.pdf', null=True, upload_to='pdf/syllabus/')),
                ('course_fee_structure', models.FileField(default='pdf/fee structure.pdf', null=True, upload_to='pdf/fee/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_categories')),
            ],
        ),
        migrations.CreateModel(
            name='course_head',
            fields=[
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200, primary_key='True', serialize=False)),
                ('card_image', models.ImageField(null=True, upload_to='images/course_image/')),
            ],
        ),
        migrations.CreateModel(
            name='course_type',
            fields=[
                ('type_id', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=200, primary_key='True', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('linked_in', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('faculty_image', models.ImageField(default='images/faculty/team.png', upload_to='images/faculty/')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('template', models.FileField(upload_to='uploaded_newsletters/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('attachement', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('program_id', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=200, primary_key='True', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slides/')),
            ],
        ),
        migrations.CreateModel(
            name='useful_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('display_image', models.ImageField(upload_to='images/useful_links/')),
                ('goto_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(help_text='Enter 10 digit Mobile number', max_length=100)),
                ('emailid', models.EmailField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('enroll_on', models.DateField(auto_now_add=True)),
                ('course_enrolling_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_details')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(default='anonymus', max_length=200)),
                ('reviewer_image', models.ImageField(default='images/review/team.png', upload_to='images/review/')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(max_length=200)),
                ('course_name', models.ForeignKey(default='Introduction To Data Science', on_delete=django.db.models.deletion.CASCADE, to='main.course_head')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='images/index/cdoe1.png', upload_to='images/index/')),
                ('welcome_header', models.CharField(max_length=200)),
                ('slider_text', models.CharField(max_length=200)),
                ('about_head', models.CharField(max_length=200)),
                ('about_body', models.TextField()),
                ('header_image', models.ImageField(null=True, upload_to='images/index/')),
                ('mission_head', models.CharField(default='Mission', max_length=200)),
                ('mission_text', models.CharField(default=' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ', max_length=500)),
                ('vission_head', models.CharField(default='Vision', max_length=200)),
                ('vission_text', models.CharField(default=' Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ', max_length=500)),
                ('num_of_online_courses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_of_dl_courses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_of_faculties', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_of_students', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('address', models.TextField()),
                ('map_link', models.URLField()),
                ('contact_num', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
                ('slides', models.ManyToManyField(to='main.slide')),
                ('useful_link', models.ManyToManyField(null=True, to='main.useful_links')),
            ],
        ),
        migrations.AddField(
            model_name='course_head',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_type'),
        ),
        migrations.AddField(
            model_name='course_head',
            name='program_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.programs'),
        ),
        migrations.AddField(
            model_name='course_details',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_head'),
        ),
        migrations.AddField(
            model_name='course_details',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
    ]
