# Generated by Django 4.0.4 on 2022-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('linked_in', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('team_image', models.ImageField(default='images/team/team.png', upload_to='images/team/')),
            ],
        ),
    ]
