# Generated by Django 4.0.4 on 2022-06-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_enrolling_for',
        ),
        migrations.DeleteModel(
            name='course_details',
        ),
    ]
