# Generated by Django 4.0.4 on 2022-06-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_course_enrolling_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('course_id', models.CharField(default='001', max_length=100, primary_key='True', serialize=False)),
                ('course_name', models.CharField(default=' enter course name', max_length=200)),
                ('card_image', models.ImageField(null=True, upload_to='images/course_image/')),
                ('display_title', models.CharField(max_length=200)),
                ('display_image', models.ImageField(upload_to='images/course_image/display_images/')),
                ('course_price', models.CharField(default='Free', max_length=200)),
                ('apply_link', models.URLField(default='#')),
                ('course_summary', models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400)),
                ('course_prerequisites', models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400)),
                ('course_eligibility', models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400)),
                ('course_syllabus', models.FileField(default='pdf/syllabus.pdf', null=True, upload_to='pdf/syllabus/')),
                ('course_fee_structure', models.FileField(default='pdf/fee structure.pdf', null=True, upload_to='pdf/fee/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_categories')),
                ('course_type', models.ForeignKey(default='undergrad', on_delete=django.db.models.deletion.CASCADE, to='main.course_type')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
                ('program_name', models.ForeignKey(default='offline', on_delete=django.db.models.deletion.CASCADE, to='main.programs')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course_enrolling_for',
            field=models.ForeignKey(default='oo', on_delete=django.db.models.deletion.CASCADE, to='main.course_details'),
        ),
    ]
