# Generated by Django 4.0.4 on 2022-06-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_details_student_course_enrolling_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course_details',
            name='display_image',
        ),
        migrations.DeleteModel(
            name='course_head',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
