# Generated by Django 4.0.4 on 2022-05-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notice',
        ),
    ]
