# Generated by Django 4.0.4 on 2022-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_notification_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
