# Generated by Django 4.0.4 on 2022-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_index_useful_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
