# Generated by Django 4.0.4 on 2022-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_announcement_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='enable',
        ),
        migrations.AddField(
            model_name='index',
            name='announcements',
            field=models.BooleanField(default=False),
        ),
    ]
