# Generated by Django 4.0.4 on 2022-06-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_index_mission_text_alter_index_vission_text'),
        ('main', '0008_remove_announcement_enable_index_announcements'),
    ]

    operations = [
    ]
