# Generated by Django 4.0.4 on 2022-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='linked_in',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
