# Generated by Django 4.0.4 on 2022-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_faculty_facebook_alter_faculty_linked_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
