# Generated by Django 4.0.4 on 2022-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_index_address_alter_index_contact_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='website',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
