# Generated by Django 4.0.4 on 2022-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_index_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_content',
            name='header_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
