# Generated by Django 4.0.4 on 2022-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_index_content_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_content',
            name='header_image',
            field=models.ImageField(null=True, upload_to='dynamic_images/'),
        ),
    ]
