# Generated by Django 4.0.4 on 2022-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_index_content_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('address', models.TextField()),
                ('contact_num', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
