# Generated by Django 4.0.4 on 2022-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_index_fb_link_alter_index_insta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='fb_link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='index',
            name='insta_link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='index',
            name='twitter_link',
            field=models.URLField(default='#'),
        ),
    ]
