# Generated by Django 4.0.4 on 2022-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_header', models.CharField(max_length=200)),
                ('about_head', models.CharField(max_length=200)),
                ('about_body', models.TextField()),
                ('header_image', models.ImageField(null=True, upload_to='static/images/index/')),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('address', models.TextField()),
                ('contact_num', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('template', models.FileField(upload_to='uploaded_newsletters/')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/slides')),
            ],
        ),
        migrations.RenameModel(
            old_name='EmailComingSoon',
            new_name='ComingSoonMailList',
        ),
        migrations.DeleteModel(
            name='footer',
        ),
        migrations.DeleteModel(
            name='index_content',
        ),
        migrations.AddField(
            model_name='index',
            name='slides',
            field=models.ManyToManyField(to='main.slide'),
        ),
    ]
