# Generated by Django 4.0.4 on 2022-06-26 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_index_fb_link_alter_index_insta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='fb_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='index',
            name='insta_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='index',
            name='num_of_dl_courses',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='index',
            name='num_of_faculties',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='index',
            name='num_of_online_courses',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='index',
            name='num_of_students',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='index',
            name='twitter_link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
