# Generated by Django 4.0.4 on 2022-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_index_newsletter_slide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='header_image',
            field=models.ImageField(null=True, upload_to='index/'),
        ),
    ]
