# Generated by Django 4.0.4 on 2022-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images/index/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.FileField(upload_to='email_templates/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='images/slides/'),
        ),
    ]
