# Generated by Django 4.0.4 on 2022-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_index_header_image_alter_newsletter_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.FileField(upload_to='uploaded_newsletters/'),
        ),
    ]
