# Generated by Django 4.0.4 on 2022-05-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_newsletter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='map_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
