# Generated by Django 4.0.4 on 2022-06-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_welcome_header_index_welcome_header_blue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='welcome_header_blue',
            new_name='welcome_header',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='welcome_header_yellow',
            new_name='welcome_header_highlighted',
        ),
    ]
