# Generated by Django 4.0.4 on 2022-05-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_newsletter_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
