# Generated by Django 4.0.4 on 2022-06-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_welcome_header_blue_index_welcome_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=200)),
                ('program_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibility', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Syllabus', models.TextField(blank=True, null=True)),
                ('Program_objective', models.TextField(blank=True, null=True)),
                ('Course_objective', models.TextField(blank=True, null=True)),
                ('fees', models.CharField(max_length=200)),
                ('apply_now', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='course_head',
            fields=[
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200, primary_key='True', serialize=False)),
                ('card_image', models.ImageField(null=True, upload_to='images/course_image/')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_type')),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.programs')),
            ],
        ),
    ]
