# Generated by Django 4.0.4 on 2022-06-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_program_course_head'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
