# Generated by Django 4.0.4 on 2022-05-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_name',
            field=models.CharField(max_length=200, primary_key='True', serialize=False),
        ),
        migrations.CreateModel(
            name='courses_header',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.programs')),
            ],
        ),
    ]
