# Generated by Django 4.0.4 on 2022-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='academic_calendar',
            field=models.FileField(default='pdf/academicCalender.pdf', null=True, upload_to='pdf/academicCalender/'),
        ),
        migrations.AddField(
            model_name='course_details',
            name='admission_process',
            field=models.CharField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=800),
        ),
        migrations.AddField(
            model_name='course_details',
            name='course_duration',
            field=models.CharField(blank='False', default='x-y months', max_length=100),
        ),
        migrations.AddField(
            model_name='course_details',
            name='documents_required',
            field=models.CharField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=500),
        ),
        migrations.DeleteModel(
            name='course_head',
        ),
    ]
