# Generated by Django 4.0.4 on 2022-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_course_details_academic_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='academic_calendar',
            field=models.FileField(default='pdf/academicCalendar.pdf', null=True, upload_to='pdf/academicCalendar/'),
        ),
    ]
