# Generated by Django 4.0.4 on 2022-06-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_course_details_academic_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='category',
        ),
        migrations.DeleteModel(
            name='course_categories',
        ),
    ]
