# Generated by Django 4.0.4 on 2022-05-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_course_type_course_head_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_head',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_type'),
        ),
    ]
