# Generated by Django 4.0.4 on 2022-05-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_index_map_link'),
        ('main', '0026_alter_course_head_course_type'),
    ]

    operations = [
    ]
