# Generated by Django 4.0.4 on 2022-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_merge_20220526_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slider_text',
            field=models.CharField(default='CDOE offers programmes of the study that are customized to meet the learning requirements of knowledge seekers as well as to ensure that they learn at their own pace and convenience', max_length=200),
            preserve_default=False,
        ),
    ]
