# Generated by Django 4.0.4 on 2022-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_course_details_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
