# Generated by Django 4.0.4 on 2022-05-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_course_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_categories',
            fields=[
                ('category_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=200, primary_key='True', serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='course_details',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_categories'),
        ),
    ]
