# Generated by Django 4.0.4 on 2022-06-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_team_github'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
