# Generated by Django 4.0.4 on 2022-05-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_index_slider_text'),
        ('main', '0029_course_categories_alter_course_details_category'),
    ]

    operations = [
    ]
