# Generated by Django 4.0.4 on 2022-06-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_course_details_course_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Detail',
            new_name='CourseDetail',
        ),
        migrations.RenameModel(
            old_name='course_type',
            new_name='CourseType',
        ),
        migrations.RenameModel(
            old_name='Useful_Link',
            new_name='UsefulLink',
        ),
    ]
