# Generated by Django 4.0.4 on 2022-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_merge_20220529_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_image',
            field=models.ImageField(default='images/faculty/team.png', upload_to='images/faculty/'),
        ),
    ]
