# Generated by Django 4.0.4 on 2022-06-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_course_detail_coursedetail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
