# Generated by Django 4.0.4 on 2022-06-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_programs_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='category',
            field=models.CharField(choices=[('General Degree', 'General Degree'), ('Professional Degree', 'Professional Degree')], default='General Degree', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='admission_process',
            field=models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='documents_required',
            field=models.TextField(default='Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400),
        ),
    ]
