# Generated by Django 4.0.4 on 2022-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_coursedetail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='specialization',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
