# Generated by Django 4.0.4 on 2022-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_course_details_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=200, primary_key='True', serialize=False)),
                ('reviewer_name', models.CharField(default='anonymus', max_length=200)),
                ('reviewer_image', models.ImageField(default='images/review/team.png', upload_to='images/review/')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('negative', models.IntegerField(editable='False')),
                ('review', models.TextField(max_length=200)),
            ],
        ),
    ]
