# Generated by Django 4.0.4 on 2022-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_coursedetail_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ugc_2f', models.FileField(default='pdf/ugc.pdf', null=True, upload_to='pdf/ugc_2f/')),
                ('ugc_12B', models.FileField(default='pdf/ugc.pdf', null=True, upload_to='pdf/ugc_12B/')),
                ('naac', models.FileField(default='pdf/ugc.pdf', null=True, upload_to='pdf/naac/')),
                ('deb_ugc', models.FileField(default='pdf/ugc.pdf', null=True, upload_to='pdf/deb_ugc/')),
                ('aicte', models.FileField(default='pdf/ugc.pdf', null=True, upload_to='pdf/aicte/')),
                ('ciqa', models.FileField(default='pdf/ugc.pdf', null=True, upload_to='pdf/ciqa/')),
            ],
        ),
    ]
