# Generated by Django 4.0.4 on 2022-05-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='negative',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
