# Generated by Django 4.0.4 on 2022-06-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_faculty_faculty_image'),
        ('main', '0035_compliance'),
    ]

    operations = [
    ]
