# Generated by Django 4.0.4 on 2022-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_merge_20220628_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_image',
            field=models.ImageField(default='images/faculty/team.png', upload_to='images/faculty/'),
        ),
    ]
