# Generated by Django 4.0.4 on 2022-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_review_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
