# Generated by Django 4.0.4 on 2022-06-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_faculty_faculty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='specialization',
            field=models.CharField(blank=True, default='()', max_length=200, null=True),
        ),
    ]
