# Generated by Django 4.0.4 on 2022-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_coursedetail_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='specialization',
            field=models.CharField(blank=True, default='.', max_length=200, null=True),
        ),
    ]
