# Generated by Django 4.0.4 on 2022-05-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_review_negative_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='negative',
        ),
    ]
