# Generated by Django 4.0 on 2022-05-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_review_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='slides',
            field=models.ManyToManyField(to='main.Slide'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(help_text='Enter 10 digit Mobile number', max_length=100)),
                ('emailid', models.EmailField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('enroll_on', models.DateField(auto_now_add=True)),
                ('course_enrolling_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_details')),
            ],
        ),
    ]
