# Generated by Django 4.0.4 on 2022-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_announcements_on_load_index_announcements_popup_on_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='website',
            field=models.TextField(blank=True, default='#', null=True),
        ),
    ]
