# Generated by Django 4.0.4 on 2022-06-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_index_slides_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_enrolling_for',
            field=models.CharField(max_length=200),
        ),
    ]
