# Generated by Django 4.0.4 on 2022-06-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_student_course_enrolling_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
