# Generated by Django 4.0.4 on 2022-06-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_index_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='card_image',
            field=models.ImageField(default='images/course_image/course_image.jpg', null=True, upload_to='images/course_image/'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='course_prerequisites',
            field=models.TextField(default='Lorem ipsum pytgravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus .', max_length=400),
        ),
    ]
