# Generated by Django 4.0.4 on 2022-06-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_faculty_about_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='about_faculty',
        ),
    ]
