# Generated by Django 4.0 on 2022-06-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_faculty_about_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_enrolling_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_head'),
        ),
    ]
