# Generated by Django 4.0.4 on 2022-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(help_text='Enter 10 digit Mobile number', max_length=100)),
                ('emailid', models.EmailField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('course_enrolling_for', models.CharField(max_length=200)),
                ('enroll_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
