# Generated by Django 4.0.4 on 2022-06-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_enrolling_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course_details'),
        ),
    ]
