# Generated by Django 4.0.4 on 2022-06-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_student_course_enrolling_for'),
        ('main', '0044_remove_faculty_about_faculty'),
    ]

    operations = [
    ]
