# Generated by Django 4.0.4 on 2022-06-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_useful_links_index_mission_head_index_mission_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='useful_link',
            field=models.ManyToManyField(null=True, to='main.useful_links'),
        ),
        migrations.AddField(
            model_name='useful_links',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useful_links',
            name='display_image',
            field=models.ImageField(upload_to='images/useful_links/'),
        ),
    ]
