# Generated by Django 4.0.4 on 2022-06-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_course_details_course_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='course_fee_structure',
            field=models.FileField(default='pdf\x0cee structure.pdf', null=True, upload_to='pdf/fee/'),
        ),
    ]
